export const getLegendaryItems = () => {
    const legendaryItems: { label: string }[] = [
        { label: '가시 갑옷' },
        { label: '갈라진 하늘' },
        { label: '강철심장' },
        { label: '강철의 솔라리 펜던트' },
        { label: '개척자' },
        { label: '거대한 히드라' },
        { label: '경계' },
        { label: '경계의 와드석' },
        { label: '고속 연사포' },
        { label: '공허의 지팡이' },
        { label: '공허한 광휘' },
        { label: '구원' },
        { label: '구인수의 격노검' },
        { label: '굶주린 히드라' },
        { label: '균열 생성기' },
        { label: '그림자 검' },
        { label: '그림자 불꽃' },
        { label: '기사의 맹세' },
        { label: '기회' },
        { label: '꿈 생성기' },
        { label: '끝없는 절망' },
        { label: '나보리 신속검' },
        { label: '내셔의 이빨' },
        { label: '대자연의 힘' },
        { label: '대천사의 지팡이' },
        { label: '대천사의 포옹' },
        { label: '도미닉 경의 인사' },
        { label: '독사의 송곳니' },
        { label: '라바돈의 죽음모자' },
        { label: '라일라이의 수정홀' },
        { label: '란두인의 예언' },
        { label: '루난의 허리케인' },
        { label: '루덴의 동반자' },
        { label: '리안드리의 고통' },
        { label: '리치베인' },
        { label: '마나무네' },
        { label: '마법공학 로켓 벨트' },
        { label: '마법사의 최후' },
        { label: '망자의 갑옷' },
        { label: '메자이의 영혼약탈자' },
        { label: '멜모셔스의 아귀' },
        { label: '모렐로노미콘' },
        { label: '몰락한 왕의 검' },
        { label: '무덤꽃' },
        { label: '무라마나' },
        { label: '무한의 대검' },
        { label: '미카엘의 축복' },
        { label: '발걸음 분쇄기' },
        { label: '밤의 끝자락' },
        { label: '밤의 수확자' },
        { label: '벤시의 장막' },
        { label: '벼락폭풍검' },
        { label: '불경한 히드라' },
        { label: '불타는 향로' },
        { label: '삼위일체' },
        { label: '새벽심장' },
        { label: '선체파괴자' },
        { label: '세계의 결실' },
        { label: '세릴다의 원한' },
        { label: '쇼진의 창' },
        { label: '수호 천사' },
        { label: '슈렐리아의 군가' },
        { label: '스태틱의 단검' },
        { label: '스테락의 도전' },
        { label: '실험적 마공학판' },
        { label: '심연의 가면' },
        { label: '악의' },
        { label: '얼어붙은 건틀릿' },
        { label: '얼어붙은 심장' },
        { label: '영겁의 지팡이' },
        { label: '오만' },
        { label: '요우무의 유령검' },
        { label: '우주의 추진력' },
        { label: '워모그의 갑옷' },
        { label: '원칙의 원형낫' },
        { label: '월석 재생기' },
        { label: '월식' },
        { label: '유령 무희' },
        { label: '자자크의 세계가시' },
        { label: '정령의 형상' },
        { label: '정수 약탈자' },
        { label: '제국의 명령' },
        { label: '존야의 모래시계' },
        { label: '종말의 겨울' },
        { label: '죽음의 무도' },
        { label: '증오의 사슬' },
        { label: '지크의 융합' },
        { label: '지평선의 초점' },
        { label: '징수의 총' },
        { label: '천상의 이의' },
        { label: '칠흑의 양날 도끼' },
        { label: '케이닉 루컨' },
        { label: '크라켄 학살자' },
        { label: '태양불꽃 방패' },
        { label: '태양의 썰매' },
        { label: '폭풍 쇄도' },
        { label: '폭풍갈퀴' },
        { label: '피바라기' },
        { label: '피의 노래' },
        { label: '필멸의 철갑궁' },
        { label: '필멸자의 운명' },
        { label: '해신작쇼' },
        { label: '헤르메스의 시미터' },
        { label: '헬리아의 메아리' },
        { label: '혹한의 손길' },
        { label: '화공 펑크 사슬검' },
        { label: '흐르는 물의 지팡이' }
    ]
    return legendaryItems
}
