import Link from "next/link";
import LogoutBtn from "./components/LogoutBtn";
import LoginBtn from "./components/LoginBtn";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { getServerSession } from "next-auth";
import { connectDB } from "@/util/database";
import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import Games from "./games/page";
import "./globals.css";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import Image from "next/image";

interface UserSession {
  user: {
    name: string;
    email: string;
  };
}

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const db = (await connectDB).db("dream");
  let session: UserSession | null = await getServerSession(authOptions);
  let result = null;
  if (session?.user) {
    result = await db.collection("user_cred").findOne({ email: session.user.email });
  }

  return (
    <html lang="en">
      <head>
      </head>
      <body className={notoSansKr.className}>
        <div className="flex flex-col max-w-full overflow-x-auto overflow-y-auto">
          <div className="navbar flex flex-wrap items-center justify-center px-4 py-2 min-w-[1200px]">
            <div className="flex items-center space-x-2 text-sm">
              <Link href="/">
                <div className="searchLogo">
                  <span className="lolS">LOL</span>
                  <span className="recordS">RECORD</span>
                </div>
              </Link>
              <Link className="hover:bg-gray-200 rounded-md" href="/lists">기록실</Link>
              <Link className="hover:bg-gray-200 rounded-md" href="/versus">상대법</Link>
              <Link className="hover:bg-gray-200 rounded-md" href="/charSearch">챔피언</Link>
              {session ? (
                <Link className="hover:bg-gray-200 rounded-md" href="/write">직접입력하기</Link>
              ) : (
                <></>
              )}
              <Games />
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger className="hover:bg-gray-200">
                <Image alt={'setting'} src="/setting.png" height={30} width={30}></Image>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                {session && (
                  <DropdownMenuLabel className="hover:bg-gray-200 text-left">
                    <Link href={"/profile/" + result._id}>{session.user.name}</Link>
                  </DropdownMenuLabel>
                )}
                <DropdownMenuSeparator />
                {!session && (
                  <DropdownMenuItem className="hover:bg-gray-200 text-left font-normal">
                    <Link href="/register">회원가입</Link>
                  </DropdownMenuItem>
                )}
                {session && (
                  <DropdownMenuItem className="hover:bg-gray-200 text-left font-normal">
                    <Link href={"/saveGameHistory"}>닉네임등록</Link>
                  </DropdownMenuItem>
                )}
                <DropdownMenuItem className="hover:bg-gray-200 text-left font-normal">
                  {session ? (<LogoutBtn />) : (<LoginBtn />)}
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          {/* 하단 콘텐츠 */}
          <main className="flex-grow min-w-[1000px] max-w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
