//layout.tsx
import Link from "next/link";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { getServerSession } from "next-auth";
import { connectDB } from "@/util/database";
import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Session } from "inspector";
console.log('메인페이지')

interface UserSession {
  user: {
    name: string;
    email: string;
  }
}
const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  let session: UserSession | null = await getServerSession(authOptions)
  const db = (await connectDB).db('dream')
  let result = null
  if (session?.user) {
    result = await db.collection('user_cred').findOne({ email: session.user.email })
  }

  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <div className="navbar">
          <Link href="/">대충사이트이름 </Link>
          <Link href="/games">게임닉네임작성 </Link>

          {
            session ? <span><Link href="/write" > 직접입력하기 </Link></span> : <Link href={"/register"}>직접입력하기</Link>

          }
          <Link href="/lists"> 전체list </Link>
          {
            result ? <Link href={"/list/" + result._id} >내list</Link> : null
          }
          {
          }
          <Link href="/aramTierList"> 칼바람티어정리 </Link>
          {
            session ? <></> : <Link href="/register"> 회원가입 </Link>
          }
          {
            session ? <span> {session.user.name} <LogoutBtn /> </span> : <LoginBtn />
          }
        </div>{children}</body>
    </html>
  );
}
