//layout.tsx
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { connectDB } from "@/util/database";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { authOptions } from "./api/auth/[...nextauth]";
import LoginBtn from "./LoginBtn";

console.log('메인페이지')

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await getServerSession(authOptions)
  const db = (await connectDB).db('dream')
  let result = null
  if (session?.user) {
    result = await db.collection('user_cred').findOne({ email: session.user.email })
  }

  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <div className="navbar">
          <Link href="/" className="logo"> 대충 사이트 이름 </Link>
          <Link href="/lists"> 전체list</Link>
          {/* {
            result ? <Link href={"/list/" + result._id}>내list</Link> : null
          } */}
          <Link href="/write" > 직접입력하기 </Link>
          {/* {
            session ? <></> : <Link href="/register"> 회원가입 </Link>
          } */}
          <LoginBtn></LoginBtn>
        </div>{children}</body>
    </html>
  );
}
