export const getChampions = () => {
    const championData: { nameN: number; nameE: string, nameK: string }[] = [
        { "nameN": 266, "nameE": "Aatrox", "nameK": "아트록스" },
        { "nameN": 103, "nameE": "Ahri", "nameK": "아리" },
        { "nameN": 84, "nameE": "Akali", "nameK": "아칼리" },
        { "nameN": 166, "nameE": "Akshan", "nameK": "아크샨" },
        { "nameN": 12, "nameE": "Alistar", "nameK": "알리스타" },
        { "nameN": 32, "nameE": "Amumu", "nameK": "아무무" },
        { "nameN": 34, "nameE": "Anivia", "nameK": "애니비아" },
        { "nameN": 1, "nameE": "Annie", "nameK": "애니" },
        { "nameN": 523, "nameE": "Aphelios", "nameK": "아펠리오스" },
        { "nameN": 22, "nameE": "Ashe", "nameK": "애쉬" },
        { "nameN": 136, "nameE": "AurelionSol", "nameK": "아우렐리온 솔" },
        { "nameN": 268, "nameE": "Azir", "nameK": "아지르" },
        { "nameN": 432, "nameE": "Bard", "nameK": "바드" },
        { "nameN": 200, "nameE": "Belveth", "nameK": "벨베스" },
        { "nameN": 53, "nameE": "Blitzcrank", "nameK": "블리츠크랭크" },
        { "nameN": 63, "nameE": "Brand", "nameK": "브랜드" },
        { "nameN": 201, "nameE": "Braum", "nameK": "브라움" },
        { "nameN": 233, "nameE": "Briar", "nameK": "브라이어" },
        { "nameN": 51, "nameE": "Caitlyn", "nameK": "케이틀린" },
        { "nameN": 164, "nameE": "Camille", "nameK": "카밀" },
        { "nameN": 69, "nameE": "Cassiopeia", "nameK": "카시오페아" },
        { "nameN": 31, "nameE": "Chogath", "nameK": "초가스" },
        { "nameN": 42, "nameE": "Corki", "nameK": "코르키" },
        { "nameN": 122, "nameE": "Darius", "nameK": "다리우스" },
        { "nameN": 131, "nameE": "Diana", "nameK": "다이애나" },
        { "nameN": 119, "nameE": "Draven", "nameK": "드레이븐" },
        { "nameN": 36, "nameE": "DrMundo", "nameK": "문도 박사" },
        { "nameN": 245, "nameE": "Ekko", "nameK": "에코" },
        { "nameN": 60, "nameE": "Elise", "nameK": "엘리스" },
        { "nameN": 28, "nameE": "Evelynn", "nameK": "이블린" },
        { "nameN": 81, "nameE": "Ezreal", "nameK": "이즈리얼" },
        { "nameN": 9, "nameE": "Fiddlesticks", "nameK": "피들스틱" },
        { "nameN": 114, "nameE": "Fiora", "nameK": "피오라" },
        { "nameN": 105, "nameE": "Fizz", "nameK": "피즈" },
        { "nameN": 3, "nameE": "Galio", "nameK": "갈리오" },
        { "nameN": 41, "nameE": "Gangplank", "nameK": "갱플랭크" },
        { "nameN": 86, "nameE": "Garen", "nameK": "가렌" },
        { "nameN": 150, "nameE": "Gnar", "nameK": "나르" },
        { "nameN": 79, "nameE": "Gragas", "nameK": "그라가스" },
        { "nameN": 104, "nameE": "Graves", "nameK": "그레이브즈" },
        { "nameN": 887, "nameE": "Gwen", "nameK": "그웬" },
        { "nameN": 120, "nameE": "Hecarim", "nameK": "헤카림" },
        { "nameN": 74, "nameE": "Heimerdinger", "nameK": "하이머딩거" },
        { "nameN": 910, "nameE": "Hwei", "nameK": " 흐웨이" },
        { "nameN": 420, "nameE": "Illaoi", "nameK": "일라오이" },
        { "nameN": 39, "nameE": "Irelia", "nameK": "이렐리아" },
        { "nameN": 427, "nameE": "Ivern", "nameK": "아이번" },
        { "nameN": 40, "nameE": "Janna", "nameK": "잔나" },
        { "nameN": 59, "nameE": "JarvanIV", "nameK": "자르반 4세" },
        { "nameN": 24, "nameE": "Jax", "nameK": "잭스" },
        { "nameN": 126, "nameE": "Jayce", "nameK": "제이스" },
        { "nameN": 202, "nameE": "Jhin", "nameK": "진" },
        { "nameN": 222, "nameE": "Jinx", "nameK": "징크스" },
        { "nameN": 145, "nameE": "Kaisa", "nameK": "카이사" },
        { "nameN": 429, "nameE": "Kalista", "nameK": "칼리스타" },
        { "nameN": 43, "nameE": "Karma", "nameK": "카르마" },
        { "nameN": 30, "nameE": "Karthus", "nameK": "카서스" },
        { "nameN": 38, "nameE": "Kassadin", "nameK": "카사딘" },
        { "nameN": 55, "nameE": "Katarina", "nameK": "카타리나" },
        { "nameN": 10, "nameE": "Kayle", "nameK": "케일" },
        { "nameN": 141, "nameE": "Kayn", "nameK": "케인" },
        { "nameN": 85, "nameE": "Kennen", "nameK": "케넨" },
        { "nameN": 121, "nameE": "Khazix", "nameK": "카직스" },
        { "nameN": 203, "nameE": "Kindred", "nameK": " 킨드레드" },
        { "nameN": 240, "nameE": "Kled", "nameK": "클레드" },
        { "nameN": 96, "nameE": "KogMaw", "nameK": "코그모" },
        { "nameN": 897, "nameE": "KSante", "nameK": "크산테" },
        { "nameN": 7, "nameE": "Leblanc", "nameK": "르블랑" },
        { "nameN": 64, "nameE": "LeeSin", "nameK": "리 신" },
        { "nameN": 89, "nameE": "Leona", "nameK": "레오나" },
        { "nameN": 876, "nameE": "Lillia", "nameK": "릴리아" },
        { "nameN": 127, "nameE": "Lissandra", "nameK": "리산드라" },
        { "nameN": 236, "nameE": "Lucian", "nameK": "루시안" },
        { "nameN": 117, "nameE": "Lulu", "nameK": "룰루" },
        { "nameN": 99, "nameE": "Lux", "nameK": "럭스" },
        { "nameN": 54, "nameE": "Malphite", "nameK": "말파이트" },
        { "nameN": 90, "nameE": "Malzahar", "nameK": "말자하" },
        { "nameN": 57, "nameE": "Maokai", "nameK": "마오카이" },
        { "nameN": 11, "nameE": "MasterYi", "nameK": "마스터 이" },
        { "nameN": 902, "nameE": "Milio", "nameK": "밀리오" },
        { "nameN": 21, "nameE": "MissFortune", "nameK": "미스포츈" },
        { "nameN": 62, "nameE": "MonkeyKing", "nameK": "오공" },
        { "nameN": 82, "nameE": "Mordekaiser", "nameK": "모데카이저" },
        { "nameN": 25, "nameE": "Morgana", "nameK": "모르가나" },
        { "nameN": 950, "nameE": "Naafiri", "nameK": "나피리" },
        { "nameN": 267, "nameE": "Nami", "nameK": "나미" },
        { "nameN": 75, "nameE": "Nasus", "nameK": "나서스" },
        { "nameN": 111, "nameE": "Nautilus", "nameK": "노틸러스" },
        { "nameN": 518, "nameE": "Neeko", "nameK": "니코" },
        { "nameN": 76, "nameE": "Nidalee", "nameK": "니달리" },
        { "nameN": 895, "nameE": "Nilah", "nameK": "닐라" },
        { "nameN": 56, "nameE": "Nocturne", "nameK": "녹턴" },
        { "nameN": 20, "nameE": "Nunu", "nameK": "누누와 윌럼프" },
        { "nameN": 2, "nameE": "Olaf", "nameK": "올라프" },
        { "nameN": 61, "nameE": "Orianna", "nameK": "오리아나" },
        { "nameN": 516, "nameE": "Ornn", "nameK": "오른" },
        { "nameN": 80, "nameE": "Pantheon", "nameK": "판테온" },
        { "nameN": 78, "nameE": "Poppy", "nameK": "뽀삐" },
        { "nameN": 555, "nameE": "Pyke", "nameK": "파이크" },
        { "nameN": 246, "nameE": "Qiyana", "nameK": "키아나" },
        { "nameN": 133, "nameE": "Quinn", "nameK": "퀸" },
        { "nameN": 497, "nameE": "Rakan", "nameK": "라칸" },
        { "nameN": 33, "nameE": "Rammus", "nameK": "람머스" },
        { "nameN": 421, "nameE": "RekSai", "nameK": "렉사이" },
        { "nameN": 526, "nameE": "Rell", "nameK": "렐" },
        { "nameN": 888, "nameE": "Renata", "nameK": "레나타 글라스크" },
        { "nameN": 58, "nameE": "Renekton", "nameK": "레넥톤" },
        { "nameN": 107, "nameE": "Rengar", "nameK": "렝가" },
        { "nameN": 92, "nameE": "Riven", "nameK": "리븐" },
        { "nameN": 68, "nameE": "Rumble", "nameK": "럼블" },
        { "nameN": 13, "nameE": "Ryze", "nameK": "라이즈" },
        { "nameN": 360, "nameE": "Samira", "nameK": "사미라" },
        { "nameN": 113, "nameE": "Sejuani", "nameK": "세주아니" },
        { "nameN": 235, "nameE": "Senna", "nameK": "세나" },
        { "nameN": 147, "nameE": "Seraphine", "nameK": "세라핀" },
        { "nameN": 875, "nameE": "Sett", "nameK": "세트" },
        { "nameN": 35, "nameE": "Shaco", "nameK": "샤코" },
        { "nameN": 98, "nameE": "Shen", "nameK": "쉔" },
        { "nameN": 102, "nameE": "Shyvana", "nameK": "쉬바나" },
        { "nameN": 27, "nameE": "Singed", "nameK": " 신지드" },
        { "nameN": 14, "nameE": "Sion", "nameK": "사이온" },
        { "nameN": 15, "nameE": "Sivir", "nameK": "시비르" },
        { "nameN": 72, "nameE": "Skarner", "nameK": "스카너" },
        { "nameN": 901, "nameE": "Smolder", "nameK": "스몰더" },
        { "nameN": 37, "nameE": "Sona", "nameK": "소나" },
        { "nameN": 16, "nameE": "Soraka", "nameK": "소라카" },
        { "nameN": 50, "nameE": "Swain", "nameK": "스웨인" },
        { "nameN": 517, "nameE": "Sylas", "nameK": "사일러스" },
        { "nameN": 134, "nameE": "Syndra", "nameK": "신드라" },
        { "nameN": 223, "nameE": "TahmKench", "nameK": "탐 켄치" },
        { "nameN": 163, "nameE": "Taliyah", "nameK": "탈리야" },
        { "nameN": 91, "nameE": "Talon", "nameK": "탈론" },
        { "nameN": 44, "nameE": "Taric", "nameK": "타릭" },
        { "nameN": 17, "nameE": "Teemo", "nameK": "티모" },
        { "nameN": 412, "nameE": "Thresh", "nameK": "쓰레쉬" },
        { "nameN": 18, "nameE": "Tristana", "nameK": "트리스타나" },
        { "nameN": 48, "nameE": "Trundle", "nameK": "트런들" },
        { "nameN": 23, "nameE": "Tryndamere", "nameK": "트린다미어" },
        { "nameN": 4, "nameE": "TwistedFate", "nameK": "트위스티드 페이트" },
        { "nameN": 29, "nameE": "Twitch", "nameK": " 트위치" },
        { "nameN": 77, "nameE": "Udyr", "nameK": "우디르" },
        { "nameN": 6, "nameE": "Urgot", "nameK": "우르곳" },
        { "nameN": 110, "nameE": "Varus", "nameK": "바루스" },
        { "nameN": 67, "nameE": "Vayne", "nameK": "베인" },
        { "nameN": 45, "nameE": "Veigar", "nameK": "베이가" },
        { "nameN": 161, "nameE": "Velkoz", "nameK": "벨코즈" },
        { "nameN": 711, "nameE": "Vex", "nameK": "벡스" },
        { "nameN": 254, "nameE": "Vi", "nameK": "바이" },
        { "nameN": 234, "nameE": "Viego", "nameK": "비에고" },
        { "nameN": 112, "nameE": "Viktor", "nameK": "빅토르" },
        { "nameN": 8, "nameE": "Vladimir", "nameK": "블라디미르" },
        { "nameN": 106, "nameE": "Volibear", "nameK": "볼리베어" },
        { "nameN": 19, "nameE": "Warwick", "nameK": "워윅" },
        { "nameN": 498, "nameE": "Xayah", "nameK": "자야" },
        { "nameN": 101, "nameE": "Xerath", "nameK": "제라스" },
        { "nameN": 5, "nameE": "XinZhao", "nameK": "신짜오" },
        { "nameN": 157, "nameE": "Yasuo", "nameK": "야스오" },
        { "nameN": 777, "nameE": "Yone", "nameK": "요네" },
        { "nameN": 83, "nameE": "Yorick", "nameK": "요릭" },
        { "nameN": 350, "nameE": "Yuumi", "nameK": "유미" },
        { "nameN": 154, "nameE": "Zac", "nameK": "자크" },
        { "nameN": 238, "nameE": "Zed", "nameK": "제드" },
        { "nameN": 221, "nameE": "Zeri", "nameK": "제리" },
        { "nameN": 115, "nameE": "Ziggs", "nameK": "직스" },
        { "nameN": 26, "nameE": "Zilean", "nameK": "질리언" },
        { "nameN": 142, "nameE": "Zoe", "nameK": "조이" },
        { "nameN": 143, "nameE": "Zyra", "nameK": "자이라" }]
    return championData
}